package migrations

// File generated by "migrate -m Ephmatch -t ephmatches create_ephmatches"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateEphmatches20190926015114 = &gormigrate.Migration{
	ID: "20190926015114_create_ephmatches",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Ephmatch struct {
			models.BaseSchema

			Seen *bool `gorm:"default:false;not null" json:"seen"`

			// Belongs to user
			UserID uint `json:"userID"`

			// Belongs to other
			OtherID uint `json:"otherID"`
		}
		return tx.AutoMigrate(&Ephmatch{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("ephmatches").Error
	},
}
