package migrations

// File generated by "migrate -m FactrakAgreement -t factrak_agreements create_factrak_agreements"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateFactrakAgreements20190729142610 = &gormigrate.Migration{
	ID: "20190729142610_create_factrak_agreements",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type FactrakAgreement struct {
			models.BaseSchema
			Agrees bool `json:"agrees"`

			// Belongs to survey
			FactrakSurveyID uint `gorm:"index:index_factrak_agreements_on_factrak_survey_id;" json:"factrakSurveyID"`

			// Belongs to user
			UserID uint `gorm:"index:index_factrak_agreements_on_user_id;" json:"userID"`
		}
		return tx.AutoMigrate(&FactrakAgreement{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("factrak_agreements").Error
	},
}
