package migrations

// File generated by "migrate -m Bulletin -t bulletins create_bulletins"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateBulletins20190722202201 = &gormigrate.Migration{
	ID: "20190722202201_create_bulletins",
	Migrate: func(tx *gorm.DB) error {
		// It's a good pratice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Bulletin struct {
			models.BaseSchema
			Type      string `json:"type"`
			Title     string `json:"title"`
			Body      string `gorm:"size:65535" json:"body"`
			StartDate string `json:"startDate"` // Date??
			EndDate   string `json:"endDate"`
			UserID    uint   `json:"userID"`
		}

		return tx.AutoMigrate(&Bulletin{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("bulletins").Error
	},
}
