package migrations

// File generated by "migrate -m Post -t posts create_posts"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreatePosts20190812232529 = &gormigrate.Migration{
	ID: "20190812232529_create_posts",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Post struct {
			models.BaseSchema

			// Belongs to user
			UserID uint `gorm:"index:index_posts_on_user_id;not null" json:"userID"`

			// Belongs to discussion
			DiscussionID uint `gorm:"index:index_posts_on_discussion_id;not null;" json:"discussionID"`

			Content string `gorm:"size:65535;not null" json:"content"`

			// This is for when a user is deleted, but we still want to keep the info.
			// Ideally, we would only soft delete users but, we need to maintain the previous WSO's
			// standards.
			ExUserName string `json:"exUserName"`
		}
		return tx.AutoMigrate(&Post{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("posts").Error
	},
}
