package migrations

// File generated by "migrate -m AreaOfStudy -t areas_of_study create_areas_of_study"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateAreasOfStudy20190729142313 = &gormigrate.Migration{
	ID: "20190729142313_create_areas_of_study",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type AreaOfStudy struct {
			models.BaseSchema
			Name         string `gorm:"unique;not null" json:"name"`
			Abbreviation string `gorm:"size:4;column:abbrev;unique;not null" json:"abbreviation"`

			// Belongs to department
			DepartmentID *uint `gorm:"not null" json:"departmentID"`
		}
		return tx.AutoMigrate(&AreaOfStudy{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("areas_of_study").Error
	},
}
