package migrations

// File generated by "migrate -m Dorm -t dorms create_dorms"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateDorms20190721040956 = &gormigrate.Migration{
	ID: "20190721040956_create_dorms",
	Migrate: func(tx *gorm.DB) error {
		// It's a good pratice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Dorm struct {
			models.BaseSchema
			NeighborhoodID    int          `json:"neighborhood_id"`
			Name              string       `json:"name"`
			KeyOrCard         *string      `json:"key_or_card"`
			Description       *string      `gorm:"size:65535" json:"description"`
			Built             *int         `json:"built"`
			Capacity          *int         `json:"capacity"`
			NumberBathrooms   *int         `json:"number_bathrooms"`
			NumberSingles     *int         `json:"number_singles"`
			NumberDoubles     *int         `json:"number_doubles"`
			NumberFlex        *int         `json:"number_flex"`
			NumberWashers     *int         `json:"number_washers"`
			BathroomRatio     *float64     `json:"bathroom_ratio"`
			Comfort           *int         `json:"comfort"`
			Loudness          *int         `json:"loudness"`
			Convenience       *int         `json:"convenience"`
			Wifi              *float64     `json:"wifi"`
			Location          *float64     `json:"location"`
			Satisfaction      *float64     `json:"satisfaction"`
			AverageSingleArea *int         `json:"average_single_area"`
			AverageDoubleArea *int         `json:"average_double_area"`
			ModeSingleArea    *int         `json:"mode_single_area"`
			ModeDoubleArea    *int         `json:"mode_double_area"`
		}
		return tx.AutoMigrate(&Dorm{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("dorms").Error
	},
}
