package migrations

// File generated by "migrate -m Office -t offices create_offices"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateOffices20190721060106 = &gormigrate.Migration{
	ID: "20190721060106_create_offices",
	Migrate: func(tx *gorm.DB) error {
		// It's a good pratice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Office struct {
			models.BaseSchema
			Number string `gorm:"unique" json:"number"`
		}
		return tx.AutoMigrate(&Office{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("offices").Error
	},
}
