package migrations

// File generated by "migrate -m User -t users add_opt_out_ephmatch_to_users"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddOptOutEphmatchToUsers20190926015139 = &gormigrate.Migration{
	ID: "20190926015139_add_opt_out_ephmatch_to_users",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema

			OptOutEphmatch *bool `gorm:"DEFAULT:false;not null" json:"optOutEphmatch"`
		}
		return tx.AutoMigrate(&User{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("users").Error
	},
}
