package migrations

// File generated by "migrate -m Tag -t tags create_tags_and_tags_users"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateTagsAndTagsUsers20190723012050 = &gormigrate.Migration{
	ID: "20190723012050_create_tags_and_tags_users",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct{}
		type Tag struct {
			models.BaseSchema
			Name  string  `gorm:"unique;"`
			Users []*User `gorm:"many2many:tags_users;"`
		}
		return tx.AutoMigrate(&Tag{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		err := tx.DropTableIfExists("tags_users").Error
		if err != nil {
			return err
		}

		return tx.DropTable("tags").Error

	},
}
