package migrations

// File generated by "migrate -m BulletinRide -t bulletin_rides create_bulletin_rides"

import (
	"time"

	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateBulletinRides20190812204834 = &gormigrate.Migration{
	ID: "20190812204834_create_bulletin_rides",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type BulletinRide struct {
			models.BaseSchema

			Body        string    `gorm:"size:65535" json:"body"`
			Date        time.Time `json:"date"`
			Offer       *bool     `gorm:"not null;" json:"offer"`
			Source      string    `gorm:"not null;" json:"source"`
			Destination string    `gorm:"not null;" json:"destination"`

			// Belongs to user
			UserID uint `json:"userID"`
		}
		return tx.AutoMigrate(&BulletinRide{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("bulletin_rides").Error
	},
}
