package migrations

// File generated by "migrate -m Neighborhood -t neighborhoods create_neighborhoods"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateNeighborhoods20190721040940 = &gormigrate.Migration{
	ID: "20190721040940_create_neighborhoods",
	Migrate: func(tx *gorm.DB) error {
		// It's a good pratice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Neighborhood struct {
			models.BaseSchema
			Name string `json:"name"`
		}
		return tx.AutoMigrate(&Neighborhood{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("neighborhoods").Error
	},
}
