package migrations

// File generated by "migrate -m Course -t courses create_courses"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateCourses20190729142528 = &gormigrate.Migration{
	ID: "20190729142528_create_courses",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Course struct {
			models.BaseSchema
			Number string `gorm:"not null" json:"number"`

			// Belongs to area of study
			AreaOfStudyID *uint `gorm:"not null" json:"areaOfStudyID"`
		}
		return tx.AutoMigrate(&Course{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("courses").Error
	},
}
