package migrations

// File generated by "migrate -m FactrakSurvey -t factrak_surveys create_factrak_surveys"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateFactrakSurveys20190729142626 = &gormigrate.Migration{
	ID: "20190729142626_create_factrak_surveys",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type FactrakSurvey struct {
			models.BaseSchema
			// Belongs to user (student)
			UserID uint `gorm:"index:index_factrak_surveys_on_user_id;not null" json:"userID"`

			// Belongs to professor
			ProfessorID uint `gorm:"index:index_factrak_surveys_on_professor_id;not null" json:"professorID"`

			// Belongs to course
			CourseID uint `gorm:"index:index_factrak_surveys_on_course_id;not null" json:"courseID"`

			WouldRecommendCourse *bool   `json:"wouldRecommendCourse"`
			CourseWorkload       *int    `json:"courseWorkload"`
			CourseStimulating    *int    `json:"courseStimulating"`
			WouldTakeAnother     *bool   `json:"wouldTakeAnother"`
			Approachability      *int    `json:"approachability"`
			LeadLecture          *int    `json:"leadLecture"`
			PromoteDiscussion    *int    `json:"promoteDiscussion"`
			OutsideHelpfulness   *int    `json:"outsideHelpfulness"`
			Comment              string  `gorm:"size:65535" json:"comment"`
			Flagged              bool    `json:"flagged"`
			GradeReceived        *string `json:"gradeReceived"`
		}
		return tx.AutoMigrate(&FactrakSurvey{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("factrak_surveys").Error
	},
}
