package migrations

// File generated by "migrate -m DormtrakReview -t dormtrak_reviews create_dormtrak_reviews"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateDormtrakReviews20190808235302 = &gormigrate.Migration{
	ID: "20190808235302_create_dormtrak_reviews",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type DormtrakReview struct {
			models.BaseSchema
			// Belongs to user (student)
			UserID uint `gorm:"index:index_dormtrak_reviews_on_user_id;not null" json:"userID"`

			// Belongs to dorm room
			DormRoomID uint `gorm:"index:index_dormtrak_reviews_on_dorm_room_id;not null" json:"dormRoomID"`

			Comment *string `gorm:"size:65535" json:"comment"`

			LivedHere        *bool   `json:"livedHere"`
			Closet           *string `json:"closet"`
			ClosetDesc       *string `gorm:"size:65535" json:"closetDesc"`
			Flooring         *string `json:"flooring"`
			CommonRoomAccess *bool   `json:"commonRoomAccess"`
			CommonRoomDesc   *string `gorm:"size:65535" json:"commonRoomDesc"`
			ThermostatAccess *bool   `json:"thermostatAccess"`
			ThermostatDesc   *string `gorm:"size:65535" json:"thermostatDesc"`
			OutletsDesc      *string `gorm:"size:65535" json:"outletsDesc"`
			KeyOrCard        *string `json:"keyOrCard"`
			Noise            *string `gorm:"size:65535" json:"noise"`
			BedAdjustable    *bool   `json:"bedAdjustable"`
			PrivateBathroom  *bool   `json:"privateBathroom"`
			BathroomDesc     *string `gorm:"size:65535" json:"bathroomDesc"`
			Comfort          *int    `json:"comfort"`
			Loudness         *int    `json:"loudness"`
			Convenience      *int    `json:"convenience"`
			Wifi             *int    `json:"wifi"`
			Location         *int    `json:"location"`
			Satisfaction     *int    `json:"satisfaction"`
		}
		return tx.AutoMigrate(&DormtrakReview{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("dormtrak_reviews").Error
	},
}
