package migrations

// File generated by "migrate -m DormRoom -t dorm_rooms create_dorm_rooms"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateDormRooms20190721041007 = &gormigrate.Migration{
	ID: "20190721041007_create_dorm_rooms",
	Migrate: func(tx *gorm.DB) error {
		// It's a good pratice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type DormRoom struct {
			models.BaseSchema
			DormID           uint     `gorm:"index:index_dorm_rooms_on_dorm_id" json:"dormID"`
			Number           string   `json:"number"`
			Closet           *string  `json:"closet"`
			Flooring         *string  `json:"flooring"`
			CommonRoomAccess *bool    `json:"commonRoomAccess"`
			CommonRoomDesc   *string  `gorm:"size:65535" json:"commonRoomDesc"`
			ThermostatAccess *bool    `json:"thermostat_access"`
			ThermostatDesc   *string  `gorm:"size:65535" json:"thermostatDesc"`
			OutletsDesc      *string  `gorm:"size:65535" json:"outletsDesc"`
			KeyOrCard        *string  `json:"keyOrCard"`
			Faces            *string  `json:"faces"`
			Noise            *string  `gorm:"size:65535" json:"noise"`
			BedAdjustable    *bool    `json:"bed_adjustable"`
			HC               *bool    `json:"hc"`
			PrivateBathroom  *bool    `json:"privateBathroom"`
			FloorNumber      *int     `json:"floorNumber"`
			Area             *int     `json:"area"`
			Walkthrough      *bool    `json:"walkthrough"`
			BathroomDesc     *string  `gorm:"size:65535" json:"bathroomDesc"`
			NumFlag          *bool    `json:"numFlag"`
			Picture          *string  `json:"picture"`
			Comfort          *float64 `json:"comfort"`
			Loudness         *float64 `json:"loudness"`
			Convenience      *float64 `json:"convenience"`
			Wifi             *float64 `json:"wifi"`
			Location         *float64 `json:"location"`
			Satisfaction     *float64 `json:"satisfaction"`
			RoomType         *string  `json:"roomType"`
		}
		return tx.AutoMigrate(&DormRoom{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("dorm_rooms").Error
	},
}
