package migrations

// File generated by "migrate -m EphmatchProfile -t ephmatch_profiles messaging_platforms_columns"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var MessagingPlatformsColumns20200525010513 = &gormigrate.Migration{
	ID: "20200525010513_messaging_platforms_columns",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchProfile struct {
			models.BaseSchema

			// Messaging platform columns
			MessagingPlatform *string `json:"messagingPlatform"`
			MessagingUsername *string `json:"messagingUsername"`
		}
		return tx.AutoMigrate(&EphmatchProfile{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		err := tx.Table("ephmatch_profiles").DropColumn("messaging_platform").Error
		if err != nil {
			return err
		}
		err = tx.Table("ephmatch_profiles").DropColumn("messaging_username").Error
		return err
	},
}
