package migrations

// File generated by "migrate -m EphmatchProfile -t ephmatch_profiles current_location_columns"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CurrentLocationColumns20200524014728 = &gormigrate.Migration{
	ID: "20200524014728_current_location_columns",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchProfile struct {
			models.BaseSchema

			LocationVisible *bool   `gorm:"DEFAULT:true;not null" json:"locationVisible"`
			LocationTown    *string `json:"locationTown"`
			LocationState   *string `json:"locationState"`
			LocationCountry *string `json:"LocationCountry"`
		}
		return tx.AutoMigrate(&EphmatchProfile{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("ephmatch_profiles").Error
	},
}
