package migrations

// File generated by "migrate -m EphmatchLike -t ephmatch_likes create_ephmatch_likes"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateEphmatchLikes20200325175722 = &gormigrate.Migration{
	ID: "20200325175722_create_ephmatch_likes",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchLike struct {
			models.BaseSchema

			// Belongs to user
			UserID uint `json:"userID"`

			// Belongs to the user that the User liked
			LikedID uint `json:"likedID"`
		}
		return tx.AutoMigrate(&EphmatchLike{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("ephmatch_likes").Error
	},
}
