package migrations

// File generated by "migrate -m EphmatchMatch -t ephmatch_matches create_ephmatch_matches"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateEphmatchMatches20200324005606 = &gormigrate.Migration{
	ID: "20200324005606_create_ephmatch_matches",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchMatch struct {
			models.BaseSchema

			// Belongs to user A (only in DB, not JSON)
			UserAID uint `gorm:"column:user_a_id;index:index_ephmatch_matches_on_user_a_id;not null;" json:"-"`

			// Belongs to user B (only in DB, not JSON)
			UserBID uint `gorm:"column:user_b_id;index:index_ephmatch_matches_on_user_b_id;not null;" json:"-"`
		}
		return tx.AutoMigrate(&EphmatchMatch{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("ephmatch_matches").Error
	},
}
