package migrations

// File generated by "migrate -m EphmatchMatch -t ephmatch_matches ephmatch_match_seen_columns"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var EphmatchMatchSeenColumns20200526221419 = &gormigrate.Migration{
	ID: "20200526221419_ephmatch_match_seen_columns",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchMatch struct {
			models.BaseSchema

			UserASeen *bool `gorm:"DEFAULT:false;not null" json:"-"`
			UserBSeen *bool `gorm:"DEFAULT:false;not null" json:"-"`
		}
		return tx.AutoMigrate(&EphmatchMatch{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		err := tx.Table("ephmatch_matches").DropColumn("user_a_seen").Error
		if err != nil {
			return err
		}
		err = tx.Table("ephmatch_matches").DropColumn("user_b_seen").Error
		return err
	},
}
