package migrations

// File generated by "migrate -m GoodrichMenuItems -t goodrich_menu_items create_goodrich_menu_items"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateGoodrichMenuItems20210426013057 = &gormigrate.Migration{
	ID: "20210426013057_create_goodrich_menu_items",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type GoodrichMenuItem struct {
			models.BaseSchema
			Title       string  `json:"title"`
			Description string  `json:"description"`
			Price       float64 `json:"price"`
			Available   bool    `json:"available"`
		}
		return tx.AutoMigrate(&GoodrichMenuItem{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("goodrich_menu_items").Error
	},
}
