package migrations

// File generated by "migrate -m GoodrichMenuOrders -t goodrich_orders create_goodrich_orders"

import (
	"time"

	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateGoodrichOrders20210426013116 = &gormigrate.Migration{
	ID: "20210426013116_create_goodrich_orders",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type GoodrichOrder struct {
			models.BaseSchema
			Status        models.GoodrichOrderStatus `json:"status"`
			PhoneNumber   string                     `json:"phoneNumber"`
			PreferredTime time.Time                  `json:"preferredTime"`
			PickupTime    *time.Time                 `json:"pickupTime"`
			Notes         string                     `json:"notes"`
			TotalPrice    float64                    `json:"totalPrice"`
			ComboDeal     *bool                      `gorm:"DEFAULT:false;not null" json:"comboDeal"`
			AdminNotes    string                     `json:"adminNotes"`

			PaymentMethod models.GoodrichPaymentMethod `json:"paymentMethod"`
			IDNumber      *string                      `json:"idNumber"`

			// You will need to make a custom format to store these in SQL, b/c a join table would be absolutely massive. I suggest doing a comma separated format like "id,id,id"
			ItemList string `json:"-"`

			// Belongs to user
			UserID uint `json:"userID"`
		}
		return tx.AutoMigrate(&GoodrichOrder{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("goodrich_orders").Error
	},
}
