package migrations

// File generated by "migrate -m User -t users user_add_on_campus_semesters_column"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var UserAddOnCampusSemestersColumn20210406005136 = &gormigrate.Migration{
	ID: "20210406005136_user_add_on_campus_semesters_column",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema
			OnCampusSemesters int `gorm:"DEFAULT:0;not null" json:"onCampusSemester"`
		}
		return tx.AutoMigrate(&User{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.Table("users").DropColumn("on_campus_semesters").Error
	},
}
