package migrations

// File generated by "migrate -m EphmatchRelation -t ephmatch_relations create_ephmatch_relations"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateEphmatchRelations20210607211439 = &gormigrate.Migration{
	ID: "20210607211439_create_ephmatch_relations",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchRelation struct {
			models.BaseSchema

			// Belongs to user
			User   *models.User `json:"user"`
			UserID uint         `gorm:"index:index_ephmatch_relations_on_user_id;not null;" json:"userID"`

			// Belongs to the user that the User has a (asymmetrical) relation with
			Other   *models.User `json:"other"`
			OtherID uint         `gorm:"index:index_ephmatch_relations_on_other_id;not null;" json:"otherID"`

			Relation string `json:"relation"`
		}
		return tx.AutoMigrate(&EphmatchRelation{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new table,
		return tx.DropTable("ephmatch_relations").Error
	},
}
