package migrations

// File generated by "migrate -m User -t users williams_id_column"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var WilliamsIdColumn20210425233453 = &gormigrate.Migration{
	ID: "20210425233453_williams_id_column",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema
			// Williams W# ID
			WilliamsID string `json:"williamsId"`
		}
		return tx.AutoMigrate(&User{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("users").DropColumn("williams_id").Error
	},
}
