package migrations

// File generated by "migrate -m GoodrichMenuItem -t goodrich_menu_items quantity_column"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var QuantityColumn20210507173142 = &gormigrate.Migration{
	ID: "20210507173142_quantity_column",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type GoodrichMenuItem struct {
			models.BaseSchema
			QuantityLimit bool `gorm:"DEFAULT:false;not null" json:"quantityLimit"`
			Quantity      *int `json:"quantity"`
		}
		return tx.AutoMigrate(&GoodrichMenuItem{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("goodrich_menu_items").DropColumn("quantity").Error
	},
}
