package migrations

// File generated by "migrate -m NotificationToken -t notification_tokens create_notification_tokens"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateNotificationTokens20210326205140 = &gormigrate.Migration{
	ID: "20210326205140_create_notification_tokens",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type NotificationToken struct {
			models.BaseSchema

			// Belongs to user
			UserID uint `gorm:"index:index_notification_tokens_on_user_id;not null" json:"userID"`

			Type  string `json:"type"`
			Token string `json:"token"`
		}
		return tx.AutoMigrate(&NotificationToken{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("notification_tokens").Error
	},
}
