package migrations

// File generated by "migrate -m FactrakSurvey -t factrak_surveys add_mh_factrak_survey_q"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddMhFactrakSurveyQ20211201012742 = &gormigrate.Migration{
	ID: "20211201012742_add_mh_factrak_survey_q",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type FactrakSurvey struct {
			models.BaseSchema
			MentalHealthSupport *int `json:"mentalHealthSupport"`
		}
		return tx.AutoMigrate(&FactrakSurvey{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("factrak_surveys").DropColumn("mental_health_support").Error
	},
}
