package migrations

// File generated by "migrate -m FactrakSurvey -t facktrak_surveys factrak_surveys_course_info_columns"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var FactrakSurveysCourseInfoColumns20210207234139 = &gormigrate.Migration{
	ID: "20210207234139_factrak_surveys_course_info_columns",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type FactrakSurvey struct {
			models.BaseSchema

			// Course info data
			SemesterSeason *string `json:"semesterSeason"` // Fall, Winter Study, Spring
			SemesterYear   *int    `json:"semesterYear"`
			CourseFormat   *string `json:"courseFormat"` // Remote, Hybrid, In-Person
		}
		return tx.AutoMigrate(&FactrakSurvey{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		err := tx.Table("factrak_surveys").DropColumn("semester_season").Error
		if err != nil {
			return err
		}
		err = tx.Table("factrak_surveys").DropColumn("semester_year").Error
		if err != nil {
			return err
		}
		err = tx.Table("factrak_surveys").DropColumn("course_format").Error
		return err
	},
}
