package migrations

// File generated by "migrate -m book -a create_table create_books"

import (
	sql_types "github.com/WilliamsStudentsOnline/wso-go/lib/sql_types"
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateBooks20221230032200 = &gormigrate.Migration{
	ID: "20221230032200_create_books",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Book struct {
			models.BaseSchema

			// Book title.
			Title string `gorm:"not null" json:"title"`
			// Book subtitle.
			Subtitle *string `json:"subtitle,omitempty"`
			// The names of the authors and/or editors for this book.
			Authors sql_types.CSV `gorm:"type:varchar(255)" json:"authors,omitempty"`
			// Publisher of this book.
			Publisher *string `json:"publisher,omitempty"`
			// ISBN-13 of this book (all books have this)
			Isbn string `gorm:"not null" json:"isbn13"`
			// URL to view information about this book on the Google Books site.
			InfoLink *string `gorm:"size:65535" json:"infoLink,omitempty"`
			// Image link for book cover (Medium)
			ImageLink *string `gorm:"size:65535" json:"imageLink,omitempty"`

			// Has many Book Listings
			BookListings []*models.BookListing `gorm:"foreignKey:BookID" json:"bookListings,omitempty"`
			// Many2Many courses
			Courses []*models.Course `gorm:"many2many:course_book;" json:"courses,omitempty"`
		}
		return tx.AutoMigrate(&Book{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.Table("table").DropColumn("books").Error
	},
}
