package migrations

// File generated by "migrate -m EphmatchProfile -t ephmatch_profiles looking_for_column"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var LookingForColumn20220504015544 = &gormigrate.Migration{
	ID: "20220504015544_looking_for_column",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type EphmatchProfile struct {
			models.BaseSchema
			LookingFor *string `json:"lookingFor"`
		}
		return tx.AutoMigrate(&EphmatchProfile{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("ephmatch_profiles").DropColumn("looking_for").Error
	},
}
