package migrations

// File generated by "migrate -m User -m AreaOfStudy -t user_areaofStudy user_add_areas_of_study"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var UserAddAreasOfStudy20220219171916 = &gormigrate.Migration{
	ID: "20220219171916_user_add_areas_of_study",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			// Many2Many Area of Studies iff professor (computed periodically from courses)
			models.BaseSchema
			AreasOfStudy []*models.AreaOfStudy `gorm:"many2many:user_areaOfStudy;" json:"areasOfStudy"`
		}
		type AreaOfStudy struct {
			models.BaseSchema
			// Many2Many professors  (computed periodically from courses)
			Professors []*models.User `gorm:"many2many:user_areaOfStudy;" json:"professors"`
		}

		return tx.AutoMigrate(&User{}, &AreaOfStudy{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("user_areaOfStudy").Error
	},
}
