package migrations

// File generated by "migrate -m BannedUser -t banned_users add_banned_users_table"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddBannedUsersTable20220228163053 = &gormigrate.Migration{
	ID: "20220228163053_add_banned_users_table",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type BannedUser struct {
			models.BaseSchema

			// Belongs to user
			UserID uint `gorm:"index:index_banned_users_on_user_id;not null;" json:"userID"`

			Reason string `json:"reason"`

			// Service access: true means allowed to access if would normally get access, false means scope will not be granted
			Factrak       bool `gorm:"default:true" json:"factrak"`
			Dormtrak      bool `gorm:"default:true" json:"dormtrak"`
			Ephcatch      bool `gorm:"default:true" json:"ephcatch"`
			BulletinRead  bool `gorm:"default:true" json:"bulletinRead"`
			BulletinWrite bool `gorm:"default:true" json:"bulletinWrite"`
			Ephmatch      bool `gorm:"default:true" json:"ephmatch"`
		}
		return tx.AutoMigrate(&BannedUser{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("banned_users").Error
	},
}
