package migrations

// File generated by "migrate -t book_listings -a create_table create_book_listings"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateBookListings20221224071254 = &gormigrate.Migration{
	ID: "20221224071254_create_book_listings",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type BookListing struct {
			models.BaseSchema

			// Book Info
			// Title: Book title.
			Title *string `gorm:"not null" json:"title,omitempty"`
			// Subtitle: Book subtitle.
			Subtitle *string `json:"subtitle,omitempty"`
			// Authors: The names of the authors and/or editors for this book.
			Authors *string `json:"authors,omitempty"`
			// Publisher: Publisher of this book.
			Publisher *string `json:"publisher,omitempty"`
			// ISBN_10: ISBN-10 of this book.
			ISBN_10 string
			// ISBN_13: ISBN-13 of this book.
			ISBN_13 string `gorm:"not null" json:"isbn13"`
			// InfoLink: URL to view information about this book on the Google
			// Books site.
			InfoLink *string `gorm:"size:65535" json:"infoLink,omitempty"`
			// ImageLink: Image link for book cover
			ImageLink *string `gorm:"size:65535" json:"imageLinks,omitempty"`

			// Listing Info

			// Belongs to user (student)
			UserID uint         `gorm:"index:index_book_listings_on_user_id;not null" json:"userID"`
			User   *models.User `json:"user,omitempty"`

			// Belongs to course
			CourseID uint           `gorm:"index:index_book_listings_on_course_id;not null" json:"courseID"`
			Course   *models.Course `json:"course,omitempty"`

			Condition   *string `json:"condition"`
			Description *string `gorm:"size:65535" json:"description"`

			// True -> Offering to buy, False -> Offering to sell
			Buy bool `json:"-"`
		}
		return tx.AutoMigrate(&BookListing{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("book_listings").Error
	},
}
