package migrations

// File generated by "migrate -m NotificationSettings -t notification_settings add_food_notify"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddFoodNotify20240111162825 = &gormigrate.Migration{
	ID: "20240111162825_add_food_notify",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type NotificationSettings struct {
			models.BaseSchema

			// Belongs to user
			UserID uint `gorm:"index:index_notification_settings_on_user_id;not null" json:"userID"`

			// Settings:
			EnableNotifications bool `json:"enableNotifications"`
			SalmonNotify        bool `json:"salmonNotify"`
			FoodNotify          bool `json:"foodNotify"`
		}
		return tx.AutoMigrate(&NotificationSettings{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("notification_settings").DropColumn("food_notify").Error
	},
}
