package migrations

// File generated by "migrate -m FeatureFlags -t feature_flags add_feature_flags"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddFeatureFlags20240123162801 = &gormigrate.Migration{
	ID: "20240123162801_add_feature_flags",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type FlagStatus string

		const (
			FlagEnabled  FlagStatus = "ENABLED"
			FlagDisabled FlagStatus = "DISABLED"
		)

		type FeatureFlags struct {
			models.BaseSchema
			Name   string     `gorm:"uniqueIndex;not null" json:"name"`
			Status FlagStatus `gorm:"not null" json:"status"`
		}
		return tx.AutoMigrate(&FeatureFlags{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("feature_flags").Error
	},
}
