package migrations

// File generated by "migrate -m User -t users user_add_dormtrak_review_deficit"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var UserAddDormtrakReviewDeficit20240109164702 = &gormigrate.Migration{
	ID: "20240109164702_user_add_dormtrak_review_deficit",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema
			DormtrakReviewDeficit *int `json:"dormtrakReviewDeficit"`
		}
		return tx.AutoMigrate(&User{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		return tx.Table("users").DropColumn("dormtrak_review_deficit").Error
	},
}
