package migrations

// File generated by "migrate create_course_scheduler_selections --path ../../../db/migrations -m course_scheduler_selection -t course_scheduler_selection -a create_table"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateCourseSchedulerSelections20240111204545 = &gormigrate.Migration{
	ID: "20240111204545_create_course_scheduler_selections",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type Model struct {
			models.BaseSchema

			Student   *models.User   `json:"student"`
			Course    *models.Course `json:"course"`
			StudentID *uint          `json:"studentID"`
			CourseID  *uint          `json:"courseID"`
			Hidden    bool           `json:"hidden"`

			Semester models.SemesterType `json:"semesterType"`
			Year     *uint               `json:"year"`
		}
		return tx.AutoMigrate(&Model{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		return tx.DropTable("course_scheduler_selection").Error
	},
}
