package migrations

// File generated by "migrate -m DiningKeyword -t user_dining_keywords add_user_dining_keywords"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddUserDiningKeywords20240110165319 = &gormigrate.Migration{
	ID: "20240110165319_add_user_dining_keywords",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema
			DiningKeywords []*models.DiningKeyword `gorm:"many2many:user_dining_keywords"`
		}
		type DiningKeyword struct {
			models.BaseSchema
			//set size limit to 30 to prevent any trolling
			Word  string         `gorm:"size:30;not null" json:"content"`
			Users []*models.User `gorm:"many2many:user_dining_keywords"`
		}
		return tx.AutoMigrate(&DiningKeyword{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("user_dining_keywords").Error
	},
}
