package migrations

// File generated by "migrate -m BulletinRide -t bulletin_rides add_ride_details"

import (
	"time"

	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddRideDetails20240116162847 = &gormigrate.Migration{
	ID: "20240116162847_add_ride_details",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type BulletinRide struct {
			// models.BaseSchema
			Body           string          `gorm:"size:65535" json:"body"`
			Date           time.Time       `json:"date"`
			Offer          *bool           `gorm:"not null" json:"offer"`
			Source         models.Location `json:"source" binding:"required" enums:",WILLIAMS,ALBANY,NYC,BOSTON,PITTSFIELD"`
			Destination    models.Location `json:"destination"  binding:"required" enums:",WILLIAMS,ALBANY,NYC,BOSTON,PITTSFIELD"`
			AvailableSeats uint            `gorm:"not null" json:"availableSeats"`
			Price          float64         `json:"price"`

			// Belongs to user
			UserID uint         `json:"userID"`
			User   *models.User `json:"user,omitempty"`
		}
		return tx.AutoMigrate(&BulletinRide{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		err := tx.Table("bulletin_rides").DropColumn("available_seats").Error
		if err != nil {
			return err
		}
		err = tx.Table("bulletin_rides").DropColumn("price").Error
		if err != nil {
			return err
		}
		err = tx.Table("bulletin_rides").DropColumn("source").Error
		if err != nil {
			return err
		}
		err = tx.Table("bulletin_rides").DropColumn("destination").Error
		return err
	},
}
