package migrations

// File generated by "migrate -m CommunitySurveyResponseModel -t community_survey_response create_community_survey_response"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateCommunitySurveyResponse20250121195354 = &gormigrate.Migration{
	ID: "20250121195354_create_community_survey_response",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type CommunitySurveyResponseModel struct {
			models.BaseSchema
		}
		return tx.AutoMigrate(&CommunitySurveyResponseModel{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("community_survey_response").Error
	},
}
