package migrations

// File generated by "migrate -m DailyMessage -t daily_messages migrate_daily_messages"

import (
	"time"

	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var MigrateDailyMessages20250502191523 = &gormigrate.Migration{
	ID: "20250502191523_migrate_daily_messages",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type DailyMessage struct {
			models.BaseSchema
			MessageID        uint      `gorm:"unique" json:"id"`
			Date             time.Time `json:"date"`
			Title            string    `json:"title"`
			ShortDescription string    `json:"short_description"`
			Description      string    `json:"description"`
			Author           string    `json:"author"`
			AuthorEmail      string    `json:"author_email"`
			Department       string    `json:"dept"`
			Venue            *string   `json:"venue"`
			Category         string    `gorm:"index_category" json:"category"`
		}
		return tx.AutoMigrate(&DailyMessage{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("daily_messages").Error
	},
}
