package migrations

// File generated by "migrate -m CommunitySurveyModel -t community_survey create_community_survey"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var CreateCommunitySurvey20250121195226 = &gormigrate.Migration{
	ID: "20250121195226_create_community_survey",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type CommunitySurvey struct {
			models.BaseSchema
			// survey info
			Question string `gorm:"size:65535" json:"question"`

			UserID uint `gorm:"index:index_user_id;not null" json:"userID"`

			// options info
			NumOptions uint   `json:"numOptions"`
			Options    string `gorm:"size:65535" json:"options"` // serialized,eg: option1;option2;option3

			// number of respondents
			ResponseCount uint `gorm:"DEFAULT:0;not null" json:"responseCount"`
		}
		return tx.AutoMigrate(&CommunitySurvey{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// TODO: do one of these, remove the other
		// For a new table,
		return tx.DropTable("community_surveys").Error
	},
}
