package migrations

// File generated by "migrate -m User -t users adding_dietary_pref_and_visibility"

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

// Add the new variable to the migrations list at db/migrate.go
// If this creates a new table, or some other feature not automatically recorded in the model, add it to
// the InitSchema section of db/migrate.go

var AddingDietaryPrefAndVisibility20260414150339 = &gormigrate.Migration{
	ID: "20260414150339_adding_dietary_pref_and_visibility",
	Migrate: func(tx *gorm.DB) error {
		// It's a good practice to copy the struct inside the function,
		// so side effects are prevented if the original struct changes during the time.
		// But, when the table already exists, it just adds new fields as columns, so just have a struct
		// with those fields.
		type User struct {
			models.BaseSchema
			DietaryPreference  *bool `gorm:"DEFAULT:false;not null"`
			DietaryPrefVisible *bool `gorm:"DEFAULT:false;not null"`
		}
		return tx.AutoMigrate(&User{}).Error
	},
	Rollback: func(tx *gorm.DB) error {
		// For a new column:
		if err := tx.Table("users").DropColumn("dietary_preference").Error; err != nil {
			return err
		}
		return tx.Table("users").DropColumn("dietary_pref_visible").Error
	},
}
