# Auto-label PRs based on changed files.
# See https://github.com/actions/labeler

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

codegen:
  - changed-files:
      - any-glob-to-any-file:
          - docs/swagger.yaml
          - docs/swagger.json
          - docs/docs.go
          - .spectral.yaml
          - .github/scripts/check-openapi.sh
          - .github/workflows/openapi.yml
