FROM wso-backend/builder-cert AS builder
FROM alpine:3.19
RUN mkdir /wso-jobs
COPY --from=builder /wso/jobs /wso-jobs
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Set timezone
COPY --from=builder /wso/zoneinfo.zip /
ENV TZ=America/NewYork
ENV ZONEINFO=/zoneinfo.zip
