FROM wso-backend/builder AS builder
FROM alpine:3.10
COPY --from=builder /go/bin/wso-backend /wso-backend
COPY --from=builder /go/src/github.com/WilliamsStudentsOnline/wso-go/config/environment /config

ENTRYPOINT ["/wso-backend"]