.\" Manpage for wso-backend.
.\" To install locally, run:
.\" install -g 0 -o -m 0644 wso-backend.1 /usr/local/man/man1
.\" gzip /usr/local/man/man1/wso-backend.1
.TH "WSO Utilities" "1" "26 October 2024" "1.0.4" "wso-backend man page"
.NM wso-backend
.SH NAME
wso-backend \- run the WSO server 
.SH SYNOPSIS
wso-backend [--config] [--development] [--verbose]
.SH DESCRIPTION
Running the
.NM
utility starts the server for WSO, which will open port 8080 and begin accepting requests. For more information please read the documentation at:

\fBhttps://github\&.com/WilliamsStudentsOnline/wso-go\fP

.SH OPTIONS
The options for
.B wso-backend
are as follows:

\fB\--config\fP
Take the first argument as a file with a valid configuration file for the server\&.
.TP
\fB\--development\fP
Enable development mode, with more log messages\&.
.TP
\fB\--verbose\fP
Enable verbose mode, which outputs logs in JSON and standard syslog format to the current directory as well as to standard output\&.
.TP

.SH SEE ALSO
\fBhttps://github\&.com/WilliamsStudentsOnline/wso-go\fP
.TP
\fBhttps://wso-dev\&.williams\&.edu/api/docs/index\&.html\fP
.SH BUGS
Yes. See the issue tracker for more information.
.SH AUTHOR
Williams Students Online
