.\" Manpage for wso-backend.
.\" To install locally, run:
.\" install -g 0 -o 0644 wso-backend.1 /usr/share/man/man1
.\" gzip /usr/share/man/man1/wso-backend.1
.TH "Williams Students Online" "2.0" "25 March 2025" "2.0" "wso-backend man page"
.SH NAME
wso-backend \- run the WSO server 
.SH SYNOPSIS
wso-backend [--config] [--development]
.SH DESCRIPTION
Running
wso-backend
starts the server for WSO, which will open port 8080 for documentation and begin accepting requests on port 80. For more information please read the documentation at \c
.UR https://github.com/WilliamsStudentsOnline/wso-go
the project's GitHub
.UE \c
\ page\&.

.SH OPTIONS
The options for
wso-backend
are as follows:
.TP
\-\-config
Take the first argument as a file with a valid configuration file for the server\&.
.TP
\-\-development
Enable development mode, with more log messages\&.

.SH SEE ALSO
See the \c
.UR https://wso-dev.williams.edu/api/docs/index.html
API documentation
.UE \c
\ for more information\&.
.SH BUGS
Yes. See the issue tracker for more information.
.SH AUTHOR
Williams Students Online
