package main

type StructType struct {
	Name       string
	Fields     []StructField
	Desc       string
	GoConvName string
}

type StructField struct {
	Name       string
	Type       string
	IsStruct   bool
	IsSlice    bool
	IsPointer  bool
	JSONTag    string
	Desc       string
	GoConvName string
}

type Entry struct {
	Name       string
	GoConvName string
	IsSlice    bool
}

const StructTemplate = `// Code generated by lib/service_responses/cmd. DO NOT EDIT.
package responses

import (
{{range .Packages}}	"{{.}}"
{{end}}
)

func Convert{{.Prefix}}(m {{if .Entry.IsSlice}}[]{{end}}*{{.Entry.GoConvName}}) {{if .Entry.IsSlice}}[]{{end}}*{{.Entry.Name}} {
{{if .Entry.IsSlice}}
	r := make([]*{{.Entry.Name}}, len(m))
	for i := range m {
		r[i] = Convert{{.Entry.Name}}(m[i])
	}
{{else}}
	r := Convert{{.Entry.Name}}(m)
{{end}}
	return r
}

{{range .Structs}}type {{.Name}} struct {
{{range .Fields}}
	{{.Name}} {{if .IsSlice}}[]{{end}}{{if or .IsPointer .IsStruct}}*{{end}}{{.Type}} ` + "`" + `json:"{{.JSONTag}}"` + "`" + `{{end}}
}

func Convert{{.Name}}(m *{{.GoConvName}}) *{{.Name}} {
	if m == nil {
		return nil
	}

	r := &{{.Name}}{}
{{range .Fields}}{{if .IsSlice}}
	r.{{.Name}} = make([]{{if or .IsPointer .IsStruct}}*{{end}}{{.Type}}, len(m.{{.GoConvName}}))
	for i := range m.{{.GoConvName}} {
		{{if .IsStruct}}r.{{.Name}}[i] = Convert{{.Type}}(m.{{.GoConvName}}[i]){{else}}r.{{.Name}}[i] = m.{{.GoConvName}}[i]{{end}}
	}{{else if .IsStruct}}
	r.{{.Name}} = Convert{{.Type}}(m.{{.GoConvName}}){{else}}
	r.{{.Name}} = m.{{.GoConvName}}{{end}}{{end}}

	return r
}

{{end}}`
