// Code generated by lib/service_responses/cmd at 2026-05-16 15:11:07.230825723 -0400 EDT m=+0.001093917. DO NOT EDIT.
package responses

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
)

func ConvertListUsersResponse(m []*models.User) []*ListUsersResponseUser {

	r := make([]*ListUsersResponseUser, len(m))
	for i := range m {
		r[i] = ConvertListUsersResponseUser(m[i])
	}

	return r
}

type ListUsersResponseDepartment struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

func ConvertListUsersResponseDepartment(m *models.Department) *ListUsersResponseDepartment {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseDepartment{}

	r.Id = m.ID
	r.Name = m.Name

	return r
}

type ListUsersResponseDorm struct {
	Id             uint   `json:"id"`
	Name           string `json:"name"`
	NeighborhoodId uint   `json:"neighborhoodID"`
}

func ConvertListUsersResponseDorm(m *models.Dorm) *ListUsersResponseDorm {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseDorm{}

	r.Id = m.ID
	r.Name = m.Name
	r.NeighborhoodId = m.NeighborhoodID

	return r
}

type ListUsersResponseDormRoom struct {
	Dorm     *ListUsersResponseDorm `json:"dorm,omitempty"`
	DormId   uint                   `json:"dormID"`
	Id       uint                   `json:"id"`
	Number   string                 `json:"number"`
	RoomType string                 `json:"roomType"`
}

func ConvertListUsersResponseDormRoom(m *models.DormRoom) *ListUsersResponseDormRoom {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseDormRoom{}

	r.Dorm = ConvertListUsersResponseDorm(m.Dorm)
	r.DormId = m.DormID
	r.Id = m.ID
	r.Number = m.Number
	r.RoomType = m.RoomType

	return r
}

type ListUsersResponseOffice struct {
	Id     uint   `json:"id"`
	Number string `json:"number"`
}

func ConvertListUsersResponseOffice(m *models.Office) *ListUsersResponseOffice {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseOffice{}

	r.Id = m.ID
	r.Number = m.Number

	return r
}

type ListUsersResponseTag struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

func ConvertListUsersResponseTag(m *models.Tag) *ListUsersResponseTag {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseTag{}

	r.Id = m.ID
	r.Name = m.Name

	return r
}

type ListUsersResponseUser struct {
	Admin                     *bool                        `json:"admin"`
	AtWilliams                *bool                        `json:"atWilliams"`
	CampusPhoneExt            *string                      `json:"campusPhoneEXT"`
	CampusStatus              *string                      `json:"campusStatus"`
	CellPhone                 *string                      `json:"cellPhone"`
	ClassYear                 *int                         `json:"classYear"`
	Department                *ListUsersResponseDepartment `json:"department,omitempty"`
	DepartmentId              *uint                        `json:"departmentID"`
	DietaryPref               *bool                        `json:"dietaryPref"`
	DietaryPrefVisible        *bool                        `json:"dietaryPrefVisible"`
	DormRoom                  *ListUsersResponseDormRoom   `json:"dormRoom,omitempty"`
	DormRoomId                *uint                        `json:"dormRoomID"`
	DormVisible               *bool                        `json:"dormVisible"`
	Entry                     *string                      `json:"entry"`
	EphcatchEligibility       *bool                        `json:"ephcatchEligibility"`
	FactrakAdmin              *bool                        `json:"factrakAdmin"`
	FactrakSurveyDeficit      *int                         `json:"factrakSurveyDeficit"`
	HasAcceptedDormtrakPolicy *bool                        `json:"hasAcceptedDormtrakPolicy"`
	HasAcceptedFactrakPolicy  *bool                        `json:"hasAcceptedFactrakPolicy"`
	HomeCountry               *string                      `json:"homeCountry"`
	HomePhone                 *string                      `json:"homePhone"`
	HomeState                 *string                      `json:"homeState"`
	HomeTown                  *string                      `json:"homeTown"`
	HomeVisible               *bool                        `json:"homeVisible"`
	HomeZip                   *string                      `json:"homeZip"`
	Id                        uint                         `json:"id"`
	Major                     *string                      `json:"major"`
	Name                      string                       `json:"name"`
	OffCampus                 *bool                        `json:"offCampus"`
	OffCycle                  *bool                        `json:"offCycle"`
	Office                    *ListUsersResponseOffice     `json:"office,omitempty"`
	OfficeId                  *uint                        `json:"officeID"`
	OptOutEphcatch            *bool                        `json:"optOutEphcatch"`
	Pronoun                   *string                      `json:"pronoun"`
	SuBox                     *string                      `json:"suBox"`
	Tags                      []*ListUsersResponseTag      `json:"tags,omitempty"`
	Title                     *string                      `json:"title"`
	Type                      string                       `json:"type"`
	UnixId                    string                       `json:"unixID"`
	Visible                   *bool                        `json:"visible"`
	WilliamsEmail             string                       `json:"williamsEmail"`
	WilliamsId                string                       `json:"williamsID"`
}

func ConvertListUsersResponseUser(m *models.User) *ListUsersResponseUser {
	if m == nil {
		return nil
	}

	r := &ListUsersResponseUser{}

	r.Admin = m.Admin
	r.AtWilliams = m.AtWilliams
	r.CampusPhoneExt = m.CampusPhoneExt
	r.CampusStatus = m.CampusStatus
	r.CellPhone = m.CellPhone
	r.ClassYear = m.ClassYear
	r.Department = ConvertListUsersResponseDepartment(m.Department)
	r.DepartmentId = m.DepartmentID
	r.DietaryPref = m.DietaryPreference
	r.DietaryPrefVisible = m.DietaryPrefVisible
	r.DormRoom = ConvertListUsersResponseDormRoom(m.DormRoom)
	r.DormRoomId = m.DormRoomID
	r.DormVisible = m.DormVisible
	r.Entry = m.Entry
	r.EphcatchEligibility = m.EphcatchEligibility
	r.FactrakAdmin = m.FactrakAdmin
	r.FactrakSurveyDeficit = m.FactrakSurveyDeficit
	r.HasAcceptedDormtrakPolicy = m.HasAcceptedDormtrakPolicy
	r.HasAcceptedFactrakPolicy = m.HasAcceptedFactrakPolicy
	r.HomeCountry = m.HomeCountry
	r.HomePhone = m.HomePhone
	r.HomeState = m.HomeState
	r.HomeTown = m.HomeTown
	r.HomeVisible = m.HomeVisible
	r.HomeZip = m.HomeZip
	r.Id = m.ID
	r.Major = m.Major
	r.Name = m.Name
	r.OffCampus = m.OffCampus
	r.OffCycle = m.OffCycle
	r.Office = ConvertListUsersResponseOffice(m.Office)
	r.OfficeId = m.OfficeID
	r.OptOutEphcatch = m.OptOutEphcatch
	r.Pronoun = m.Pronoun
	r.SuBox = m.SUBox
	r.Tags = make([]*ListUsersResponseTag, len(m.Tags))
	for i := range m.Tags {
		r.Tags[i] = ConvertListUsersResponseTag(m.Tags[i])
	}
	r.Title = m.Title
	r.Type = m.Type
	r.UnixId = m.UnixID
	r.Visible = m.Visible
	r.WilliamsEmail = m.WilliamsEmail
	r.WilliamsId = m.WilliamsID

	return r
}
