// +build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

func main() {
	path := "../data"

	path, err := filepath.Abs(path)
	if err != nil {
		log.Fatal("path error: " + err.Error())
		return
	}

	dormPath := filepath.Join(path, "dorms.csv")
	roomsPath := filepath.Join(path, "rooms")

	dormData, err := ioutil.ReadFile(dormPath)
	if err != nil {
		log.Fatal("dorm.csv error: " + err.Error())
		return
	}

	roomFiles, err := ioutil.ReadDir(roomsPath)
	if err != nil {
		log.Fatal("rooms error: " + err.Error())
		return
	}

	roomsData := make(map[string]string)
	for _, file := range roomFiles {
		roomFilePath := filepath.Join(roomsPath, file.Name())
		roomFileData, err := ioutil.ReadFile(roomFilePath)
		if err != nil {
			log.Fatal(file.Name() + " error: " + err.Error())
			return
		}

		roomsData[file.Name()] = string(roomFileData)
	}

	f, err := os.Create("data.go")
	if err != nil {
		log.Fatal("data.go error: " + err.Error())
		return
	}
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		DormsCSV  string
		Rooms     map[string]string
	}{
		Timestamp: time.Now(),
		DormsCSV:  string(dormData),
		Rooms:     roomsData,
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// {{ .Timestamp }}
package main

const dormsCSV = ` + "`" + `{{.DormsCSV}}` + "`" + `

var roomCSVs = map[string]string{
{{range $key, $val := .Rooms }}
	"{{$key}}": ` + "`" + `{{$val}}` + "`" + `,
{{end}}
}
`))
