apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso-backend-deployment
spec:
  selector:
    matchLabels:
      app: wso-go
      tier: backend
  replicas: 1 # tells deployment to run X pods matching the template
  template:
    metadata:
      labels:
        app: wso-go
        tier: backend
    spec:
      containers:
        - name: wso-go
          image: wso-backend:0.0.1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP