---
env: development
secrets_file: config/secrets.yaml
database_type: mysql
mysql_user: root
mysql_host: 127.0.0.1
mysql_port: 3306
mysql_database: wso
mysql_args:
  parseTime: "true"
  charset: utf8mb4
  multiStatements: "true"
redis_addr: 127.0.0.1:6379
jwt_realm: wso-go-dev
port: 8080
disable_ldap: true
jwt_timeout_hours: 168
enable_api_docs: true
hostname: localhost
jwt_identity_timeout_hours: 4272
jwt_api_timeout_hours: 168
log_formats: ['console']
