kind: PersistentVolume
apiVersion: v1
metadata:
  name: dev-mysql-pv-volume
spec:
  storageClassName: dev-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql-pv-volume"