---
jwt_secret_key: wso-jwt-development-secret
mysql_password: secret-mysql-password

## Only need this to test LDAP.
#wso_ldap_dn: cn=foo,ou=bar,o=baz
#wso_ldap_password: foobar

# note: for ADLDAP, we can use any Williams username and password
#adldap_dn: CN=<your Williams unix>,OU=student,OU=williams,DC=ad,DC=williams,DC=edu
#adldap_password: <your Williams password>

# This credential comes from OIT
#odirldap_dn: <from OIT>
#odirldap_password: <password from OIT>

#goodrich_email_password: <deprecated>