//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"encoding/json"
	"go/format"
	"io/ioutil"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

type WSOJSON struct {
	W []string `json:"w"`
	S []string `json:"s"`
	O []string `json:"o"`
}

func main() {
	path := "./words.json"

	path, err := filepath.Abs(path)
	if err != nil {
		panic(err)
	}

	wordsData, err := ioutil.ReadFile(path)
	if err != nil {
		panic(err)
	}

	wsoJson := WSOJSON{}
	err = json.Unmarshal(wordsData, &wsoJson)
	if err != nil {
		panic(err)
	}

	buf := new(bytes.Buffer)

	err = packageTemplate.Execute(buf, struct {
		Timestamp time.Time
		WSOJson   WSOJSON
	}{
		Timestamp: time.Now(),
		WSOJson:   wsoJson,
	})
	if err != nil {
		panic(err)
	}

	p, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	f, err := os.Create("words_data.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	_, err = f.Write(p)
	if err != nil {
		panic(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// {{ .Timestamp }}
package words

var wWords = []string{
{{range .WSOJson.W}}"{{.}}",
{{end}}
}

var sWords = []string{
{{range .WSOJson.S}}"{{.}}",
{{end}}
}

var oWords = []string{
{{range .WSOJson.O}}"{{.}}",
{{end}}
}
`))
