apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 1 # tells deployment to run X pods matching the template
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: wso-go
          image: wso-backend:latest
          args: ["--config=/etc/configs/config.yaml"]
          imagePullPolicy: Never
          env:
            - name: WSO_SECRET_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/etc/config-secrets"
              name: config-secret
              readOnly: true
            - mountPath: "/etc/configs"
              name: config
              readOnly: true
      volumes:
        - name: config-secret
          secret:
            secretName: backend-config-secrets
        - name: config
          configMap:
            name: backend-config