apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: wso

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - pod-role.yaml