// Code generated by lib/service_responses/cmd at 2020-01-29 14:48:16.961158 -0500 EST m=+0.001411161. DO NOT EDIT.
package responses

import (
	"github.com/WilliamsStudentsOnline/wso-go/models"
	"time"
)

func ConvertListMatchesResponse(m []*models.Ephmatch) []*ListMatchesResponseEphmatch {

	r := make([]*ListMatchesResponseEphmatch, len(m))
	for i := range m {
		r[i] = ConvertListMatchesResponseEphmatch(m[i])
	}

	return r
}

type ListMatchesResponseEphmatch struct {
	CreatedAt time.Time                 `json:"createdAt"`
	Id        uint                      `json:"id"`
	Other     *ListMatchesResponseOther `json:"other,omitempty"`
	OtherID   uint                      `json:"otherID"`
	Seen      *bool                     `json:"seen"`
}

func ConvertListMatchesResponseEphmatch(m *models.Ephmatch) *ListMatchesResponseEphmatch {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseEphmatch{}

	r.CreatedAt = m.CreatedAt
	r.Id = m.ID
	r.Other = ConvertListMatchesResponseOther(m.Other)
	r.OtherID = m.OtherID
	r.Seen = m.Seen

	return r
}

type ListMatchesResponseEphmatchProfile struct {
	Description  *string `json:"description"`
	MatchMessage *string `json:"matchMessage"`
}

func ConvertListMatchesResponseEphmatchProfile(m *models.EphmatchProfile) *ListMatchesResponseEphmatchProfile {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseEphmatchProfile{}

	r.Description = m.Description
	r.MatchMessage = m.MatchMessage

	return r
}

type ListMatchesResponseOther struct {
	ClassYear       *int                                `json:"classYear"`
	Entry           *string                             `json:"entry"`
	EphmatchProfile *ListMatchesResponseEphmatchProfile `json:"ephmatchProfile,omitempty"`
	Id              uint                                `json:"id"`
	Major           *string                             `json:"major"`
	Name            string                              `json:"name"`
	Nickname        *string                             `json:"nickname"`
	OffCycle        *bool                               `json:"offCycle"`
	Pronoun         *string                             `json:"pronoun"`
	Tags            []*ListMatchesResponseTag           `json:"tags,omitempty"`
	Title           *string                             `json:"title"`
	UnixID          string                              `json:"unixID"`
	WilliamsEmail   string                              `json:"williamsEmail"`
}

func ConvertListMatchesResponseOther(m *models.User) *ListMatchesResponseOther {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseOther{}

	r.ClassYear = m.ClassYear
	r.Entry = m.Entry
	r.EphmatchProfile = ConvertListMatchesResponseEphmatchProfile(m.EphmatchProfile)
	r.Id = m.ID
	r.Major = m.Major
	r.Name = m.Name
	r.Nickname = m.Nickname
	r.OffCycle = m.OffCycle
	r.Pronoun = m.Pronoun
	r.Tags = make([]*ListMatchesResponseTag, len(m.Tags))
	for i := range m.Tags {
		r.Tags[i] = ConvertListMatchesResponseTag(m.Tags[i])
	}
	r.Title = m.Title
	r.UnixID = m.UnixID
	r.WilliamsEmail = m.WilliamsEmail

	return r
}

type ListMatchesResponseTag struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

func ConvertListMatchesResponseTag(m *models.Tag) *ListMatchesResponseTag {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseTag{}

	r.Id = m.ID
	r.Name = m.Name

	return r
}
