// Code generated by lib/service_responses/cmd at 2020-05-23 20:35:29.804242 -0700 PDT m=+0.001524173. DO NOT EDIT.
package responses

import (
	"time"

	"github.com/WilliamsStudentsOnline/wso-go/models"
)

func ConvertListMatchesResponse(m []*models.EphmatchMatch) []*ListMatchesResponseEphmatchMatch {

	r := make([]*ListMatchesResponseEphmatchMatch, len(m))
	for i := range m {
		r[i] = ConvertListMatchesResponseEphmatchMatch(m[i])
	}

	return r
}

type ListMatchesResponseEphmatchMatch struct {
	CreatedAt     time.Time                       `json:"createdAt"`
	Id            uint                            `json:"id"`
	MatchedUser   *ListMatchesResponseMatchedUser `json:"matchedUser,omitempty"`
	MatchedUserID uint                            `json:"matchedUserID"`
	UpdatedAt     time.Time                       `json:"updatedAt"`
}

func ConvertListMatchesResponseEphmatchMatch(m *models.EphmatchMatch) *ListMatchesResponseEphmatchMatch {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseEphmatchMatch{}

	r.CreatedAt = m.CreatedAt
	r.Id = m.ID
	r.MatchedUser = ConvertListMatchesResponseMatchedUser(m.MatchedUser)
	r.MatchedUserID = m.MatchedUserID
	r.UpdatedAt = m.UpdatedAt

	return r
}

type ListMatchesResponseEphmatchProfile struct {
	Description     *string `json:"description"`
	LocationCountry *string `json:"locationCountry"`
	LocationState   *string `json:"locationState"`
	LocationTown    *string `json:"locationTown"`
	LocationVisible *bool   `json:"locationVisible"`
	MatchMessage    *string `json:"matchMessage"`
}

func ConvertListMatchesResponseEphmatchProfile(m *models.EphmatchProfile) *ListMatchesResponseEphmatchProfile {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseEphmatchProfile{}

	r.Description = m.Description
	r.LocationCountry = m.LocationCountry
	r.LocationState = m.LocationState
	r.LocationTown = m.LocationTown
	r.LocationVisible = m.LocationVisible
	r.MatchMessage = m.MatchMessage

	return r
}

type ListMatchesResponseMatchedUser struct {
	ClassYear       *int                                `json:"classYear"`
	Entry           *string                             `json:"entry"`
	EphmatchProfile *ListMatchesResponseEphmatchProfile `json:"ephmatchProfile,omitempty"`
	Id              uint                                `json:"id"`
	Major           *string                             `json:"major"`
	Name            string                              `json:"name"`
	Nickname        *string                             `json:"nickname"`
	OffCycle        *bool                               `json:"offCycle"`
	Pronoun         *string                             `json:"pronoun"`
	Tags            []*ListMatchesResponseTag           `json:"tags,omitempty"`
	Title           *string                             `json:"title"`
	UnixID          string                              `json:"unixID"`
	WilliamsEmail   string                              `json:"williamsEmail"`
}

func ConvertListMatchesResponseMatchedUser(m *models.User) *ListMatchesResponseMatchedUser {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseMatchedUser{}

	r.ClassYear = m.ClassYear
	r.Entry = m.Entry
	r.EphmatchProfile = ConvertListMatchesResponseEphmatchProfile(m.EphmatchProfile)
	r.Id = m.ID
	r.Major = m.Major
	r.Name = m.Name
	r.Nickname = m.Nickname
	r.OffCycle = m.OffCycle
	r.Pronoun = m.Pronoun
	r.Tags = make([]*ListMatchesResponseTag, len(m.Tags))
	for i := range m.Tags {
		r.Tags[i] = ConvertListMatchesResponseTag(m.Tags[i])
	}
	r.Title = m.Title
	r.UnixID = m.UnixID
	r.WilliamsEmail = m.WilliamsEmail

	return r
}

type ListMatchesResponseTag struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}

func ConvertListMatchesResponseTag(m *models.Tag) *ListMatchesResponseTag {
	if m == nil {
		return nil
	}

	r := &ListMatchesResponseTag{}

	r.Id = m.ID
	r.Name = m.Name

	return r
}
